apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp-unprivileged-{{ include "dp-conceptual-search-api.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:unprivileged
subjects:
- kind: ServiceAccount
  name: {{ include "dp-conceptual-search-api.serviceAccountName" . }}
