apiVersion: v1
kind: Service
metadata:
  name: {{ include "dp-conceptual-alpha.fullname" . }}
  labels:
    component: api
    {{- include "dp-conceptual-alpha.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    component: api
    {{- include "dp-conceptual-alpha.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-elasticsearch"
  labels:
    component: elasticsearch
    {{- include "dp-conceptual-alpha.labels" . | nindent 4 }}
spec:
  type: {{ .Values.elasticsearch.service.type }}
  ports:
    - port: {{ .Values.elasticsearch.service.port }}
      targetPort: es1
      protocol: TCP
      name: es1
  selector:
    component: elasticsearch
    {{- include "dp-conceptual-alpha.selectorLabels" . | nindent 4 }}
